package cn.imppp.knowlege.constant

enum class FileTagEnum(val tag: Int,
                       val message: String,
                       val titleMessage: String) {
    PREPARE_TAG(1, "出发准备", "应急小分队出发前准备"),
    THINGS_PREPARE(2, "物资准备", "物资准备"),
    PRO_PREPARE(3, "专业准备与装备", "专业准备与装备"),
    TRAN_PREPARE(4, "交通和后勤保障", "交通和后勤保障"),
    THINGS_PREPARE_FLAG1(5, "生活用品", "生活用品"),
    THINGS_PREPARE_FLAG2(6, "通讯设备", "通讯设备"),
    THINGS_PREPARE_FLAG3(7, "个人防护设备", "个人防护设备"),

    // 流行病调查
    DISEASE_QUERY(8, "流调步骤", "现场流行病学调查步骤"),
    DISEASE_PREPARE(9, "组织准备", "组织准备"),
    DISEASE_CONFIRM(10, "核实病例诊断", "核实病例诊断"),
    DISEASE_EXSIT(11, "确定暴发或流行的存在", "确定暴发或流行的存在"),
    DISEASE_BUILD(12, "建立病例定义", "建立病例定义"),
    DISEASE_COUNT(13, "核实病例并计算病例数", "核实病例并计算病例数"),
    DISEASE_ANY(14, "描述性分析", "描述性分析"),
    DISEASE_IDEA(15, "建立并验证假设", "建立并验证假设"),
    DISEASE_ADVICE(16, "采取控制措施", "采取控制措施"),
    DISEASE_FINISH(17, "完善现场调查", "完善现场调查"),
    DISEASE_REPORT(18, "书面报告", "书面报告"),

    // 群体性不明原因疾病现场调查处置要点
    SOCIAL_DEAL(19, "群体性不明事件", "群体性不明原因疾病现场调查处置要点"),
    SOCIAL_CONFIRM(20, "核实与判断", "核实与判断"),
    SOCIAL_ANY(21, "病例调查及分析", "病例调查及分析"),
    SOCIAL_CHECK(22, "样本采集和实验室检测", "样本采集和实验室检测"),
    SOCIAL_CONTROL(23, "现场控制措施", "现场控制措施"),
    SOCIAL_ANY1(24, "病例搜索", "病例搜索"),
    SOCIAL_ANY2(25, "初步分析", "初步分析"),
    SOCIAL_ANY3(26, "提出病因假设", "提出病因假设"),
    SOCIAL_ANY4(27, "验证病因", "验证病因"),
    SOCIAL_ANY5(28, "判断和预测", "判断和预测"),
    SOCIAL_CHECK1(29, "感染性疾病标本", "感染性疾病标本"),
    SOCIAL_CHECK2(30, "非感染性疾病标本", "非感染性疾病标本"),
    //    SOCIAL_CHECK3(31, "实验室检测", "实验室检测"),
    SOCIAL_CONTROL1(32, "无传染性的不明原因疾病", "无传染性的不明原因疾病"),
    SOCIAL_CONTROL2(33, "有传染性的不明原因疾病", "有传染性的不明原因疾病"),

    // 病媒生物应急控制要点
    CRITICAL_CONTROL(34, "病媒控制", "病媒生物应急控制要点"),
    CRITICAL_BASE_REQUIRE(35, "基本要求", "现场病媒生物控制的基本要求"),
    CRITICAL_MOUSE_DEAL(36, "现场鼠类防制", "现场鼠类防制"),
    CRITICAL_WEN_DEAL(37, "现场蚊类防制", "现场蚊类防制"),
    CRITICAL_YING_DEAL(38, "现场蝇类防制", "现场蝇类防制"),
    CRITICAL_BASE_REQUIRE1(39, "准备工作要充足", "准备工作要充足"),
    CRITICAL_BASE_REQUIRE2(40, "具体操作要规范", "具体操作要规范"),
    CRITICAL_BASE_REQUIRE3(41, "结束工作要做细", "结束工作要做细"),
    CRITICAL_MOUSE_DEAL1(42, "灭鼠原则", "灭鼠的原则"),
    CRITICAL_MOUSE_DEAL2(43, "灭鼠方法", "鼠类控制方法"),
    CRITICAL_MOUSE_DEAL3(44, "灭鼠药物", "常用灭鼠药物"),
    CRITICAL_MOUSE_DEAL4(45, "投放毒饵的量和时间", "投放毒饵的量和时间"),
    CRITICAL_MOUSE_DEAL5(46, "投放毒饵的要求", "投放毒饵的要求"),
    CRITICAL_MOUSE_DEAL6(47, "注意事项", "注意事项"),
    CRITICAL_MOUSE_DEAL7(48, "鼠情监测", "鼠情监测"),
    CRITICAL_WEN_DEAL1(49, "环境治理", "环境治理"),
    CRITICAL_WEN_DEAL2(50, "防蚊驱蚊", "防蚊驱蚊"),
    CRITICAL_WEN_DEAL3(10086, "蚊类化学控制", "蚊类化学控制"),
    CRITICAL_YING_DEAL1(51, "环境治理", "环境治理"),
    CRITICAL_YING_DEAL2(52, "蝇类控制", "蝇类控制"),

    // 调查总结报告的撰写
    REPORT_WRITING(53, "总结报告", "调查总结报告的撰写"),
    WORK_REPORT(54, "业务调查报告", "业务调查总结报告"),
    GOVERMENT_REPORT(55, "行政调查报告", "行政调查报告"),
    WORK_REPORT1(56, "标题", "标题"),
    WORK_REPORT2(57, "前言", "前言"),
    WORK_REPORT3(58, "基本情况", "基本情况"),
    WORK_REPORT4(59, "流行特点", "流行特点（流行强度、三间分布、相关图表）"),
    WORK_REPORT5(60, "临床特点及诊断标准", "临床特点及诊断标准"),
    WORK_REPORT6(61, "流行因素分析", "流行因素分析（包括分析流行病学的应用、采样与检测）"),
    WORK_REPORT7(62, "防制措施与效果评价", "防制措施与效果评价"),
    WORK_REPORT8(63, "建议", "建议"),
    WORK_REPORT9(64, "小结", "小结"),
    WORK_REPORT10(65, "报告单位和报告日期", "报告单位和报告日期"),
    GOVERMENT_REPORT1(66, "标题", "标题"),
    GOVERMENT_REPORT2(67, "前言", "前言"),
    GOVERMENT_REPORT3(68, "事件概况", "事件概况"),
    GOVERMENT_REPORT4(69, "已采取的措施及效果评价", "已采取的措施及效果评价"),
    GOVERMENT_REPORT5(70, "调查结论与趋势分析", "调查结论与趋势分析"),
    GOVERMENT_REPORT6(71, "下一步建议", "下一步建议"),
    GOVERMENT_REPORT7(72, "报告单位和报告日期", "报告单位和报告日期"),

    // 应急相关工具包
    TOOL_PACKAGE(73, "应急相关工具包", "应急相关工具包"),

    // 突发公共安全事件相关信息报告范围与标准
    EVENT_RULE(74, "事件报告", "突发公共安全事件相关信息报告范围与标准"),
    RECURSION_EVENT(75, "传染病", "传染病"),
    FOOD_EVENT(76, "食物中毒", "食物中毒"),
    JOB_EVENT(77, "职业中毒", "职业中毒"),
    OTHER_EVENT(78, "其他中毒", "其他中毒"),
    NATURE_EVENT(79, "环境因素事件", "环境因素事件"),
    X_EVENT(80, "意外辐射照射事件", "意外辐射照射事件"),
    LOSS_EVENT(81, "传染病菌、毒种丢失", "传染病菌、毒种丢失"),
    BAD_EVENT(82, "预防接种和预防服药群体性不良反应", "预防接种和预防服药群体性不良反应"),
    HOSPITAL_EVENT(83, "医源性感染事件", "医源性感染事件"),
    NO_REASON_EVENT(84, "群体性不明原因疾病", "群体性不明原因疾病"),
    THINK_EVENT(85, "其它突发公共卫生事件", "各级人民政府卫生行政部门认定的其它突发公共卫生事件"),
    RECURSION_EVENT1(86, "鼠疫", "鼠疫"),
    RECURSION_EVENT2(87, "霍乱", "霍乱"),
    RECURSION_EVENT3(88, "传染性非典型肺炎", "传染性非典型肺炎"),
    RECURSION_EVENT4(89, "人感染高致病性禽流感", "人感染高致病性禽流感"),
    RECURSION_EVENT5(90, "炭疽", "炭疽"),
    RECURSION_EVENT6(91, "甲肝/戊肝", "甲肝/戊肝"),
    RECURSION_EVENT7(92, "伤寒（副伤寒）", "伤寒（副伤寒）"),
    RECURSION_EVENT8(93, "细菌性和阿米巴性痢疾", "细菌性和阿米巴性痢疾"),
    RECURSION_EVENT9(94, "麻疹", "麻疹"),
    RECURSION_EVENT10(95, "风疹", "风疹"),
    RECURSION_EVENT11(96, "流行性脑脊髓膜炎", "流行性脑脊髓膜炎"),
    RECURSION_EVENT12(97, "登革热", "登革热"),
    RECURSION_EVENT13(98, "流行性出血热", "流行性出血热"),
    RECURSION_EVENT14(99, "钩端螺旋体病", "钩端螺旋体病"),
    RECURSION_EVENT15(100, "流行性乙型脑炎", "流行性乙型脑炎"),
    RECURSION_EVENT16(101, "疟疾", "疟疾"),
    RECURSION_EVENT17(102, "血吸虫病", "血吸虫病"),
    RECURSION_EVENT18(103, "流感", "流感"),
    RECURSION_EVENT19(104, "流行性腮腺炎", "流行性腮腺炎"),
    RECURSION_EVENT20(105, "感染性腹泻（除霍乱、痢疾、伤寒和副伤寒以外）", "感染性腹泻（除霍乱、痢疾、伤寒和副伤寒以外）"),
    RECURSION_EVENT21(106, "猩红热", "猩红热"),
    RECURSION_EVENT22(107, "水痘", "水痘"),
    RECURSION_EVENT23(108, "输血性乙肝、丙肝、HIV", "输血性乙肝、丙肝、HIV"),
    RECURSION_EVENT24(109, "新发或再发传染病", "新发或再发传染病"),
    RECURSION_EVENT25(110, "不明原因肺炎", "不明原因肺炎"),

    // 几种急性传染病的潜伏期、隔离期与接触者观察期
    STATE_TIME(111, "急性传染病观察期", "几种急性传染病的潜伏期、隔离期与接触者观察期"),
    CANCER_DISEASE(112, "病毒性肝炎", "病毒性肝炎"),
    HEAD_DISEASE(113, "流行性乙型脑炎", "流行性乙型脑炎"),
    GREY_DISEASE(114, "脊髓灰质炎", "脊髓灰质炎"),
    DOG_DISEASE(115, "狂犬病", "狂犬病"),
    POP_HEAD_DISEASE(116, "流行性感冒", "流行性感冒"),
    MA_ZHEN(117, "麻疹", "麻疹"),
    SHUI_DOU(118, "水痘", "水痘"),
    SAI_XIAN(119, "流行性腮腺炎", "流行性腮腺炎"),
    DENG_GE_RE(120, "登革热", "登革热"),
    ZENG_DUO_ZHENG(121, "传染性单核细胞增多症", "传染性单核细胞增多症"),
    AIDS(122, "艾滋病", "艾滋病"),
    HUANG_RE_BING(123, "黄热病", "黄热病"),
    SHANG_HAN(124, "流行性斑疹伤寒", "流行性斑疹伤寒"),
    FU_SHANG(125, "伤寒、副伤寒甲、乙", "伤寒、副伤寒甲、乙"),    //
    NUE_JI(126, "细菌性痢疾", "细菌性痢疾"),
    HUO_LUAN(127, "霍乱", "霍乱"),
    GAN_JUN(128, "布氏杆菌病", "布氏杆菌病"),
    SHU_YI(129, "鼠疫", "鼠疫"),        //
    TAN_JU(130, "炭疽", "炭疽"),
    BAI_HOU(131, "白喉", "白喉"),
    BAI_RI_KE(132, "百日咳", "百日咳"),
    XING_HONG_RE(133, "猩红热", "猩红热"),
    NAO_JI_SUI(134, "流行性脑脊髓膜炎", "流行性脑脊髓膜炎"),
    LUO_XUAN_BING(135, "钩端螺旋体病", "钩端螺旋体病"),
    HUI_GUI_RE(136, "回归热（虱传）", "回归热（虱传）"),

    CANCER_DISEASE1(137, "甲型", "甲型"),
    CANCER_DISEASE2(138, "乙型", "乙型"),
    CANCER_DISEASE3(139, "丙型肝炎", "丙型肝炎"),
    CANCER_DISEASE4(140, "丁型", "丁型"),
    CANCER_DISEASE5(141, "戊型", "戊型"),
    FU_SHANG1(142, "伤寒", "伤寒"),
    FU_SHANG2(143, "副伤寒", "副伤寒"),
    SHU_YI1(144, "腺鼠疫", "腺鼠疫"),
    SHU_YI2(145, "肺鼠疫", "肺鼠疫"),

    // 临床综合征划分的疾病特征
    STUDY_DISEASE(146, "疾病识别", "按临床综合征划分的疾病特征"),
    STUDY_DISEASE1(147, "无特征性皮疹的发热",
            "无特征性皮疹的发热"),
    STUDY_DISEASE2(148, "有特征性皮疹的发热",
            "有特征性皮疹的发热"),
    STUDY_DISEASE3(149, "发热伴出血",
            "发热伴出血"),
    STUDY_DISEASE4(150, "发热伴淋巴结肿大",
            "发热伴淋巴结肿大"),
    STUDY_DISEASE5(151, "发热伴神经系统表现", "发热伴神经系统表现"),
    STUDY_DISEASE6(152, "发热伴呼吸道症状", "发热伴呼吸道症状"),
    STUDY_DISEASE7(153, "发热伴胃肠道症状",
            "发热伴胃肠道症状"),
    STUDY_DISEASE8(154, "发热伴黄疸", "发热伴黄疸"),
    STUDY_DISEASE9(155, "非发热性疾病", "非发热性疾病"),
    STUDY_DISEASE1_1(156, "所有气候", "所有气候"),
    STUDY_DISEASE1_2(157, "温暖气候或季节", "温暖气候或季节"),
    STUDY_DISEASE2_1(158, "一般性皮疹（斑疹或紫癜）", "一般性皮疹（斑疹或紫癜）"),
    STUDY_DISEASE2_2(159, "一般性皮疹（疱疹或脓疱疹）", "一般性皮疹（疱疹或脓疱疹）"),
    STUDY_DISEASE2_3(160, "局部性红斑（任何部位）", "局部性红斑（任何部位）"),
    STUDY_DISEASE3_1(161, "蚊虫传播", "蚊虫传播"),
    STUDY_DISEASE3_2(162, "蜱传播", "蜱传播"),
    STUDY_DISEASE3_3(163, "啮齿动物传播", "啮齿动物传播"),
    STUDY_DISEASE3_4(164, "病媒不明", "病媒不明"),
    STUDY_DISEASE4_1(165, "全身性淋巴结肿大", "全身性淋巴结肿大"),
    STUDY_DISEASE4_2(166, "局部性淋巴结肿大", "局部性淋巴结肿大"),
    STUDY_DISEASE5_1(167, "瘫痪", "瘫痪"),
    STUDY_DISEASE5_2(168, "脑膜炎", "脑膜炎"),
    STUDY_DISEASE5_3(169, "脑炎", "脑炎"),
    STUDY_DISEASE5_4(170, "有各种致病因子引起的脑膜脑炎", "有各种致病因子引起的脑膜脑炎"),
    STUDY_DISEASE6_1(171, "上呼吸道", "上呼吸道（喉、气管、支气管）"),
    STUDY_DISEASE6_2(172, "下呼吸道", "下呼吸道（细支气管、肺泡）"),
    STUDY_DISEASE7_1(173, "腹泻", "腹泻"),
    STUDY_DISEASE7_2(174, "痢疾", "痢疾"),
    STUDY_DISEASE7_3(175, "其它", "其它"),
    STUDY_DISEASE9_1(176, "皮疹", "皮疹"),
    STUDY_DISEASE9_2(177, "神经系统疾病", "神经系统疾病"),
    STUDY_DISEASE9_3(178, "呼吸系统疾病", "呼吸系统疾病"),
    STUDY_DISEASE9_4(179, "胃肠道疾病", "胃肠道疾病"),
    STUDY_DISEASE9_5(180, "食物中毒", "食物中毒"),
    STUDY_DISEASE9_6(181, "黄疸", "黄疸"),
    STUDY_DISEASE9_7(182, "结合膜炎", "结合膜炎"),
    STUDY_DISEASE9_8(183, "泌尿道疾病", "泌尿道疾病"),

    // 急性不明原因中毒相关体征的甄别
    CHECK_DRUGS(184, "急性不明原因中毒甄别", "急性不明原因中毒相关体征的甄别"),
    SMELL_WRONG(185, "气味异常", "气味异常"),
    DUO_HAN(186, "多汗", "多汗"),
    SKIN_COLOR(187, "皮肤色泽", "皮肤色泽"),
    SMELL_WRONG1(188, "酒精味", "酒精味"),
    SMELL_WRONG2(189, "芳香味", "芳香味"),
    SMELL_WRONG3(190, "臭蛋味", "臭蛋味"),
    SMELL_WRONG4(191, "刺鼻味", "刺鼻味"),
    SMELL_WRONG5(192, "苦杏仁味", "苦杏仁味"),
    SMELL_WRONG6(193, "蒜味", "蒜味"),
    SMELL_WRONG7(194, "腐鱼味", "腐鱼味"),
    SMELL_WRONG8(195, "水果味", "水果味"),
    SMELL_WRONG9(196, "干草味", "干草味"),
    SMELL_WRONG10(197, "醋味", "醋味"),
    SMELL_WRONG11(198, "鞋油味", "鞋油味"),
    SMELL_WRONG12(199, "梨味", "梨味"),
    SMELL_WRONG13(200, "更多", "更多"),
    DUO_HAN1(201, "全身性多汗", "全身性多汗"),
    DUO_HAN2(202, "早期出现大汗淋漓", "早期出现大汗淋漓"),
    DUO_HAN3(203, "局部性多汗", "局部性多汗"),
    DUO_HAN4(204, "病程中出现多汗", "病程中出现多汗"),
    SKIN_COLOR1(205, "高铁血红蛋白症所导致的青紫", "高铁血红蛋白症所导致的青紫"),
    SKIN_COLOR2(206, "樱桃红色", "樱桃红色"),
    SKIN_COLOR3(207, "黄疸", "黄疸"),
    SKIN_COLOR4(208, "潮红色", "潮红色"),
    SKIN_COLOR5(209, "双手黄染", "双手黄染"),
    SKIN_COLOR6(210, "皮肤损害", "皮肤损害"),

    // 不明原因疾病样本采集表
    COLLECT_TABLE(211, "不明病因样本采集", "不明原因疾病样本采集表"),
    DISEASE_COLLECT1(212, "发热伴呼吸道症状", "发热伴呼吸道症状"),
    DISEASE_COLLECT2(213, "发热伴消化道症状", "发热伴消化道症状"),
    DISEASE_COLLECT3(214, "发热伴皮疹", "发热伴皮疹"),
    DISEASE_COLLECT4(215, "发热伴神经系统症状", "发热伴神经系统症状"),
    DISEASE_COLLECT5(216, "发热伴肝和肾功能损伤", "发热伴肾和肝功能损伤"),
    DISEASE_COLLECT6(217, "发热伴心脏损伤", "发热伴心脏损伤"),
    DISEASE_COLLECT7(218, "发热伴其他症状", "发热伴其他症状"),
    DISEASE_COLLECT8(219, "食物中毒", "食物中毒"),
    DISEASE_COLLECT9(220, "职业中毒", "职业中毒"),

    //  各类食物中毒特点及处理要点
    FOOD_DRUGS_DEAL(221, "食物中毒处理", "各类食物中毒特点及处理要点"),
    FOOD_DRUGS_DEAL1(222, "化学性食物中毒", "化学性食物中毒"),
    FOOD_DRUGS_DEAL2(223, "细菌性食物中毒", "细菌性食物中毒"),
    FOOD_DRUGS_DEAL3(224, "真菌毒素食物中毒", "真菌毒素食物中毒"),
    FOOD_DRUGS_DEAL4(225, "有毒动物食物中毒", "有毒动物食物中毒"),
    FOOD_DRUGS_DEAL5(226, "有毒植物食物中毒", "有毒植物食物中毒"),

    // 灾区饮用水水源选择、保护及消毒方法
    WATER_USE_FUNCTION(227, "饮用水", "灾区饮用水水源选择、保护及消毒方法"),
    WATER_CHOOSE(228, "饮用水源的选择", "饮用水源的选择"),
    KEEP_WATER(229, "饮用水水源的保护", "饮用水水源的保护"),
    DEAL_WATER(230, "水质的处理与消毒", "水质的处理与消毒"),
    CLEAR_WATER(231, "使用一体化净水设备", "使用一体化净水设备"),
    TRAN_WATER(232, "运送安全卫生水", "运送安全卫生水"),
    RECOVER_WATER(233, "自然灾害恢复期的供水设施消毒", "自然灾害恢复期的供水设施消毒"),
    CHECK_WATER(234, "饮水水质检测", "饮用水质检测"),
    KEEP_WATER1(235, "防止毒害污染", "灾前做好充分准备，防止有毒有害物的污染"),
    KEEP_WATER2(236, "防止人为污染", "饮用水源要防止人为污染"),
    DEAL_WATER1(237, "缸（桶）水", "缸（桶）水消毒处理"),
    DEAL_WATER2(238, "手压井", "手压井的消毒"),
    DEAL_WATER3(239, "大口井", "大口井的消毒"),
    DEAL_WATER4(240, "被淹没的自来水厂", "被淹没的自来水厂的水质处理及消毒"),

    // 传染病防控现场消毒方法
    KILL_VIRUS(241, "现场消毒方法", "传染病防控现场消毒方法"),
    DI_MIAN(242, "地面、墙壁", "地面、墙壁"),
    PAI_XIE(243, "病人排泄物和呕吐物", "病人排泄物和呕吐物"),
    RONG_QI(244, "盛排泄物和呕吐物的容器", "盛排泄物和呕吐物的容器"),
    CE_SUO(245, "厕所", "厕所"),
    ROOM_AIR(246, "室内空气", "室内空气"),
    WU_SHUI(247, "污水处理", "污水处理"),
    LA_JI(248, "垃圾", "垃圾"),
    CLOTH(249, "衣物", "衣物"),
    CAN_JU(250, "餐（饮）具", "餐（饮）具"),
    FOOD(251, "食物", "食物"),
    THING(252, "物品、家具、玩具", "物品、家具、玩具"),
    BOOK(253, "纸张、书报", "纸张、书报"),
    BING_REN(254, "病人尸体", "病人尸体"),
    ANIMAL_SHI_TI(255, "动物尸体", "动物尸体"),
    YUN_SHU_TOOL(256, "运输工具", "运输工具"),
    HAND_SKIN(257, "手和皮肤", "手和皮肤"),

    // 自然灾害后灾区病媒生物监测和测评
    NATURE_MONITOR(258, "灾区管理", "灾后管理"),
    MIE_MONITOR(259, "病媒生物监测", "病媒生物监测"),
    WORK_USE(260, "病媒生物防治工作实施及效果评价", "病媒生物防治工作实施及效果评价"),
    MIE_MONITOR1(261, "蚊虫密度监测", "蚊虫密度监测"),
    MIE_MONITOR2(262, "蝇类密度监测", "蝇类密度监测"),
    MIE_MONITOR3(263, "鼠类密度监测", "鼠类密度监测"),
    WORK_USE1(264, "实施杀虫、灭鼠工作的参考指标", "实施杀虫、灭鼠工作的参考指标"),
    WORK_USE2(265, "杀虫、灭鼠效果的评价", "杀虫、灭鼠效果的评价"),

    // 化学中毒常用解毒剂
    OPEN_VIRUS(266, "解毒剂", "化学物中毒常用特效解毒剂"),
    QING_VIRUS(267, "氰化物中毒解毒药", "氰化物中毒解毒药"),
    JIN_SHU_VITUS(268, "金属与类金属中毒解毒药", "金属与类金属中毒解毒药"),
    LIN_VIRUS(269, "有机磷农药中毒解毒剂", "有机磷农药中毒解毒剂"),
    BEN_VIRUS(270, "苯胺、硝基苯类中毒解毒药", "苯胺、硝基苯类中毒解毒药"),
    MOUSE_VIRUS(271, "鼠类及其他解毒剂", "鼠类及其他解毒剂"),
    QING_VIRUS1(272, "亚硝酸异戊酯", "亚硝酸异戊酯"),
    QING_VIRUS2(273, "亚硝酸钠", "亚硝酸钠"),
    QING_VIRUS3(274, "硫代硫酸钠", "硫代硫酸钠"),
    QING_VIRUS4(275, "4-二甲基苯酚(4-DMAP)", "4-二甲基苯酚(4-DMAP)"),
    QING_VIRUS5(276, "对氨基苯丙酮（PAPP）", "对氨基苯丙酮（PAPP）"),
    JIN_SHU_VITUS1(277, "依地酸二钠钙", "依地酸二钠钙"),
    JIN_SHU_VITUS2(278, "基丙磺酸钠，解砷灵", "基丙磺酸钠，解砷灵"),
    JIN_SHU_VITUS3(279, "二巯基丁二酸钠", "二巯基丁二酸钠"),
    JIN_SHU_VITUS4(280, "二巯基丙醇", "二巯基丙醇"),
    JIN_SHU_VITUS5(281, "促排灵(DTPA)", "促排灵(DTPA)"),
    JIN_SHU_VITUS6(282, "巯乙胺", "巯乙胺"),
    JIN_SHU_VITUS7(283, "巯丙甘", "巯丙甘"),
    JIN_SHU_VITUS8(284, "青霉胺", "青霉胺"),
    JIN_SHU_VITUS9(285, "普鲁士蓝", "普鲁士蓝"),
    JIN_SHU_VITUS10(286, "硫酸钠，芒硝", "硫酸钠，芒硝"),
    JIN_SHU_VITUS11(287, "喷替酸钙钠", "喷替酸钙钠"),
    LIN_VIRUS1(288, "双复磷", "双复磷"),
    LIN_VIRUS2(289, "氯解磷定", "氯解磷定"),
    LIN_VIRUS3(290, "碘解磷定", "碘解磷定"),
    BEN_VIRUS1(291, "美蓝", "美蓝"),
    MOUSE_VIRUS1(292, "乙酰胺", "乙酰胺"),
    MOUSE_VIRUS2(293, "维生素K1", "维生素K1"),
    MOUSE_VIRUS3(294, "纳络酮", "纳络酮"),

    // 疫苗免疫程序
    KEEP_FUNCTION(295, "疫苗流程", "疫苗免疫程序"),
    KEEP_FUNCTION1(296, "乙肝疫苗", "乙肝疫苗"),
    KEEP_FUNCTION2(297, "卡介苗", "卡介苗"),
    KEEP_FUNCTION3(298, "脊灰疫苗", "脊灰疫苗"),
    KEEP_FUNCTION4(299, "百白破疫苗", "百白破疫苗"),
    KEEP_FUNCTION5(300, "白破疫苗", "白破疫苗"),
    KEEP_FUNCTION6(301, "麻风疫苗（麻疹疫苗）", "麻风疫苗（麻疹疫苗）"),
    KEEP_FUNCTION7(302, "麻腮风疫苗(麻腮疫苗、麻疹疫苗)", "麻腮风疫苗(麻腮疫苗、麻疹疫苗)"),
    KEEP_FUNCTION8(303, "乙脑减毒活疫苗", "乙脑减毒活疫苗"),
    KEEP_FUNCTION9(304, "A群流脑疫苗", "A群流脑疫苗"),
    KEEP_FUNCTION10(305, "A+C流脑疫苗", "A+C流脑疫苗"),
    KEEP_FUNCTION11(306, "甲肝减毒活疫苗", "甲肝减毒活疫苗"),
    KEEP_FUNCTION12(307, "出血热疫苗(双价)", "出血热疫苗(双价)"),
    KEEP_FUNCTION13(308, "炭疽疫苗", "炭疽疫苗"),
    KEEP_FUNCTION14(309, "钩体疫苗", "钩体疫苗"),
    KEEP_FUNCTION15(310, "乙脑灭活疫苗", "乙脑灭活疫苗"),
    KEEP_FUNCTION16(311, "甲肝灭活疫苗", "甲肝灭活疫苗"),

    // 突发事件防护用品装备及使用目录
    HIDDEN_EVENT(312, "防护装备", "突发事件防护用品装备及使用目录"),
    MEI_QI_EVENT(313, "气体中毒防护", "突发煤气中毒事件"),
    HU_XI(314, "呼吸道防护", "呼吸道防护用品配备标准及使用目录"),
    CANG_DAO(315, "肠道传染病防护", "肠道传染病防护用品标准及使用说明"),
    XIAN_CHANG(316, "生活保障物资", "现场应急队伍生活保障用品一线储备清单"),
    HU_XI1(317, "一级防护标准", "一级防护标准"),
    HU_XI2(318, "二级防护标准", "二级防护标准"),
    HU_XI3(319, "三级防护标准", "三级防护标准"),
    CANG_DAO1(320, "防护装备", "防护装备"),
    CANG_DAO2(321, "使用说明", "使用说明"),


    // 蚊类处理
    WEN_CONTROL(322, "蚊类化学控制", "蚊类化学控制"),
    WEN_CONTROL1(323, "蚊幼的化学防制", "蚊幼的化学防制"),
    WEN_CONTROL2(324, "成蚊的化学控制", "成蚊的化学控制"),
    WEN_CONTROL1_1(325, "蚊幼的化学防制", "蚊幼的化学防制"),
    WEN_CONTROL1_2(326, "适合杀灭蚊虫幼虫的化学杀虫剂（WHO）", "适合杀灭蚊虫幼虫的化学杀虫剂（WHO）"),
    WEN_CONTROL2_1(327, "室内常量喷洒", "室内常量喷洒"),
    WEN_CONTROL2_2(328, "室内超低容量喷洒", "室内超低容量喷洒"),
    WEN_CONTROL2_3(329, "外环境超低容量喷洒", "外环境超低容量喷洒"),
    WEN_CONTROL2_4(330, "滞留处理", "滞留处理"),
    WEN_CONTROL2_5(331, "可以用于室内滞留喷洒的化学杀虫剂（WHO）", "可以用于室内滞留喷洒的化学杀虫剂（WHO）"),
    WEN_CONTROL2_6(332, "蚊帐浸泡", "蚊帐浸泡"),
    WEN_CONTROL2_7(333, "处理不同织物的蚊帐所需要的杀虫剂的剂量（WHO）", "处理不同织物的蚊帐所需要的杀虫剂的剂量（WHO）"),

    // 试剂
    WEN_CONTROL1_2_1(334, "汽油", "汽油"),
    WEN_CONTROL1_2_2(335, "柴油", "柴油"),
    WEN_CONTROL1_2_3(336, "杀幼油", "杀幼油"),
    WEN_CONTROL1_2_4(337, "巴黎绿", "巴黎绿"),
    WEN_CONTROL1_2_5(338, "有机磷", "有机磷"),
    WEN_CONTROL1_2_6(339, "昆虫生长调剂", "昆虫生长调剂"),
    WEN_CONTROL1_2_5_1(340, "毒死蜱", "毒死蜱"),
    WEN_CONTROL1_2_5_2(341, "杀螟松", "杀螟松"),
    WEN_CONTROL1_2_5_3(342, "倍硫磷", "倍硫磷"),
    WEN_CONTROL1_2_5_4(343, "碘硫磷", "碘硫磷"),
    WEN_CONTROL1_2_5_5(344, "马拉硫磷", "马拉硫磷"),
    WEN_CONTROL1_2_5_6(345, "甲嘧硫磷", "甲嘧硫磷"),
    WEN_CONTROL1_2_5_7(346, "双硫磷", "双硫磷"),
    WEN_CONTROL1_2_6_1(347, "灭幼脲", "灭幼脲"),
    WEN_CONTROL1_2_6_2(348, "甲氧保幼激素", "甲氧保幼激素"),
    WEN_CONTROL1_2_6_3(349, "蚊蝇醚", "蚊蝇醚"),
    WEN_CONTROL2_5_1(350, "有机磷", "有机磷"),
    WEN_CONTROL2_5_2(351, "氨基甲酸酯", "氨基甲酸酯"),
    WEN_CONTROL2_5_3(352, "拟除虫菊酯", "拟除虫菊酯"),
    WEN_CONTROL2_5_1_1(353, "马拉硫磷", "马拉硫磷"),
    WEN_CONTROL2_5_1_2(354, "杀螟松", "杀螟松"),
    WEN_CONTROL2_5_1_3(355, "甲嘧硫磷", "甲嘧硫磷"),
    WEN_CONTROL2_5_2_1(356, "恶虫威", "恶虫威"),
    WEN_CONTROL2_5_2_2(357, "残杀威", "残杀威"),
    WEN_CONTROL2_5_3_1(358, "顺式氯氰菊酯", "顺式氯氰菊酯"),
    WEN_CONTROL2_5_3_2(359, "氟氯氰菊酯", "氟氯氰菊酯"),
    WEN_CONTROL2_5_3_3(360, "氯氰菊酯", "氯氰菊酯"),
    WEN_CONTROL2_5_3_4(361, "三氟氯氰菊酯", "三氟氯氰菊酯"),
    WEN_CONTROL2_5_3_5(362, "溴氰菊酯", "溴氰菊酯"),
    WEN_CONTROL2_5_3_6(363, "二氯苯醚菊酯", "二氯苯醚菊酯"),
    WEN_CONTROL2_7_1(364, "大孔网(大于2mm)", "大孔网(大于2mm)"),
    WEN_CONTROL2_7_2(365, "标准蚊帐(1.5mm)", "标准蚊帐(1.5mm)"),

    // new add

    SHA_CHILD_CONG(373, "杀灭幼虫", "杀灭幼虫"),
    CHENG_YING_KONG_ZHI(374, "成蝇控制", "成蝇控制"),
    SHA_CHILD_CONG1(375, "常用灭蝇幼虫的杀虫剂", "常用灭蝇幼虫的杀虫剂"),
    CHENG_YING_KONG_ZHI1(376, "滞留喷洒", "滞留喷洒"),
    CHENG_YING_KONG_ZHI2(377, "空间喷雾", "空间喷雾"),
    CHENG_YING_KONG_ZHI3(378, "毒饵灭蝇", "毒饵灭蝇"),

    LINC_CHUANG_ZHENG_ZHUANG1(379, "临床症状", "临床症状"),
    LINC_CHUANG_ZHENG_ZHUANG2(380, "临床症状", "临床症状"),
    LINC_CHUANG_ZHENG_ZHUANG3(381, "临床症状", "临床症状"),
    LINC_CHUANG_ZHENG_ZHUANG4(382, "临床症状", "临床症状"),
    LINC_CHUANG_ZHENG_ZHUANG5(383, "临床症状", "临床症状"),
    LINC_CHUANG_ZHENG_ZHUANG6(384, "临床症状", "临床症状"),
    LINC_CHUANG_ZHENG_ZHUANG7(385, "临床症状", "临床症状"),
    LINC_CHUANG_ZHENG_ZHUANG8(386, "临床症状", "临床症状"),
    LINC_CHUANG_ZHENG_ZHUANG9(387, "临床症状", "临床症状"),


    FUNCTION1(388, "诱蚊灯法", "诱蚊灯法"),
    FUNCTION2(389, "人工小时法", "人工小时法"),
    FUNCTION3(390, "粘蝇条（纸）法", "粘蝇条（纸）法"),
    FUNCTION4(391, "目测法", "目测法"),
    FUNCTION5(392, "毒饵盗食法", "毒饵盗食法"),
    FUNCTION6(393, "鼠迹法", "鼠迹法"),
    FUNCTION7(394, "鼠夹法", "鼠夹法"),


    // 从临床症状入手寻找病因线索的步骤
    REASON_STEP(405, "从临床症状寻找病因", "从临床症状入手寻找病因线索的步骤"),
    QUICK_DISEASE(406, "急性感染性疾病可能性大",
            "急性感染性疾病可能性大"),
    QUICK_NO_DISEASE(407, "急性非感染性疾病可能性大",
            "急性非感染性疾病可能性大"),
    LIN_CHUANG_TE_ZHENG(408, "临床特征", "临床特征"),
    QUICK_NO_DISEASE1(409, "急性非感染性疾病特征", "急性非感染性疾病特征"),
    QUICK_NO_DISEASE2(410, "急性中毒可能性大", " 急性中毒可能性大"),
    QUICK_NO_DISEASE3(411, "群体性心因性反应可能性大", "群体性心因性反应可能性大"),
    QUICK_DISEASE1(412, "急性感染性疾病特征", "急性感染性疾病特征"),
    QUICK_DISEASE2(413, "血常规", "血常规"),
    QUICK_DISEASE3(414, "可能感染途径", "可能感染途径"),
    QUICK_NO_DISEASE21(415, "急性中毒可能性临床现象", " 急性中毒可能性临床现象"),
    QUICK_NO_DISEASE22(416, "可疑的致病毒物", " 可疑的致病毒物"),
    QUICK_NO_DISEASE31(417, "群体性心因性反应临床现象", " 群体性心因性反应临床现象"),
    QUICK_NO_DISEASE32(418, "群体性心因性反应时间的确定", " 群体性心因性反应时间的确定"),

    // 自然灾害界面
    THINGS_PREPARE_FLAG31(430, "呼吸道传染病防护用品", "呼吸道传染病防护用品"),
    THINGS_PREPARE_FLAG32(431, "自然疫源性传染病防护用品", "自然疫源性传染病防护用品"),
    THINGS_PREPARE_FLAG33(432, "台风洪涝灾害防护用品", "台风洪涝灾害防护用品"),

    PEOPLE_DUTY(12306, "队员职责", "应急队员职责"),
}