package cn.imppp.knowlege.factory;

import java.util.ArrayList;
import java.util.List;

import cn.imppp.knowlege.constant.FileTagEnum;
import cn.imppp.knowlege.entity.QueryBean;

/**
 * @ClassName: QueryFactory
 * @Author: qaq
 * @Description: 查询接口
 * @Date: 2020/10/10 8:49 AM
 * @Company: 杭州达恒科技
 * @Version: 1.0
 */

public class QueryFactory {
    private final static QueryFactory query = new QueryFactory();

    public static QueryFactory getInstance() {
        return query;
    }

    // 获取数据类
    public List<QueryBean> getRepository() {
        List<QueryBean> mList = new ArrayList<>();
        QueryBean queryBean = new QueryBean(FileTagEnum.PREPARE_TAG.getTag(), FileTagEnum.PREPARE_TAG.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.THINGS_PREPARE.getTag(), FileTagEnum.THINGS_PREPARE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.PRO_PREPARE.getTag(), FileTagEnum.PRO_PREPARE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.TRAN_PREPARE.getTag(), FileTagEnum.TRAN_PREPARE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.THINGS_PREPARE_FLAG1.getTag(), FileTagEnum.THINGS_PREPARE_FLAG1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.THINGS_PREPARE_FLAG2.getTag(), FileTagEnum.THINGS_PREPARE_FLAG2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.THINGS_PREPARE_FLAG3.getTag(), FileTagEnum.THINGS_PREPARE_FLAG3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_QUERY.getTag(), FileTagEnum.DISEASE_QUERY.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_PREPARE.getTag(), FileTagEnum.DISEASE_PREPARE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_CONFIRM.getTag(), FileTagEnum.DISEASE_CONFIRM.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_EXSIT.getTag(), FileTagEnum.DISEASE_EXSIT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_BUILD.getTag(), FileTagEnum.DISEASE_BUILD.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_COUNT.getTag(), FileTagEnum.DISEASE_COUNT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_ANY.getTag(), FileTagEnum.DISEASE_ANY.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_IDEA.getTag(), FileTagEnum.DISEASE_IDEA.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_ADVICE.getTag(), FileTagEnum.DISEASE_ADVICE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_FINISH.getTag(), FileTagEnum.DISEASE_FINISH.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_REPORT.getTag(), FileTagEnum.DISEASE_REPORT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_DEAL.getTag(), FileTagEnum.SOCIAL_DEAL.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_CONFIRM.getTag(), FileTagEnum.SOCIAL_CONFIRM.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_ANY.getTag(), FileTagEnum.SOCIAL_ANY.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_CHECK.getTag(), FileTagEnum.SOCIAL_CHECK.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_CONTROL.getTag(), FileTagEnum.SOCIAL_CONTROL.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_ANY1.getTag(), FileTagEnum.SOCIAL_ANY1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_ANY2.getTag(), FileTagEnum.SOCIAL_ANY2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_ANY3.getTag(), FileTagEnum.SOCIAL_ANY3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_ANY4.getTag(), FileTagEnum.SOCIAL_ANY4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_ANY5.getTag(), FileTagEnum.SOCIAL_ANY5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_CHECK1.getTag(), FileTagEnum.SOCIAL_CHECK1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_CHECK2.getTag(), FileTagEnum.SOCIAL_CHECK2.getTitleMessage());
        mList.add(queryBean);
//        queryBean = new QueryBean(FileTagEnum.SOCIAL_CHECK3.getTag(), FileTagEnum.SOCIAL_CHECK3.getTitleMessage());
//        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_CONTROL1.getTag(), FileTagEnum.SOCIAL_CONTROL1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SOCIAL_CONTROL2.getTag(), FileTagEnum.SOCIAL_CONTROL2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_CONTROL.getTag(), FileTagEnum.CRITICAL_CONTROL.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_BASE_REQUIRE.getTag(), FileTagEnum.CRITICAL_BASE_REQUIRE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_MOUSE_DEAL.getTag(), FileTagEnum.CRITICAL_MOUSE_DEAL.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_WEN_DEAL.getTag(), FileTagEnum.CRITICAL_WEN_DEAL.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_YING_DEAL.getTag(), FileTagEnum.CRITICAL_YING_DEAL.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_BASE_REQUIRE1.getTag(), FileTagEnum.CRITICAL_BASE_REQUIRE1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_BASE_REQUIRE2.getTag(), FileTagEnum.CRITICAL_BASE_REQUIRE2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_BASE_REQUIRE3.getTag(), FileTagEnum.CRITICAL_BASE_REQUIRE3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_MOUSE_DEAL1.getTag(), FileTagEnum.CRITICAL_MOUSE_DEAL1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_MOUSE_DEAL2.getTag(), FileTagEnum.CRITICAL_MOUSE_DEAL2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_MOUSE_DEAL3.getTag(), FileTagEnum.CRITICAL_MOUSE_DEAL3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_MOUSE_DEAL4.getTag(), FileTagEnum.CRITICAL_MOUSE_DEAL4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_MOUSE_DEAL5.getTag(), FileTagEnum.CRITICAL_MOUSE_DEAL5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_MOUSE_DEAL6.getTag(), FileTagEnum.CRITICAL_MOUSE_DEAL6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_MOUSE_DEAL7.getTag(), FileTagEnum.CRITICAL_MOUSE_DEAL7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_WEN_DEAL1.getTag(), FileTagEnum.CRITICAL_WEN_DEAL1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_WEN_DEAL2.getTag(), FileTagEnum.CRITICAL_WEN_DEAL2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_WEN_DEAL3.getTag(), FileTagEnum.CRITICAL_WEN_DEAL3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_YING_DEAL1.getTag(), FileTagEnum.CRITICAL_YING_DEAL1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CRITICAL_YING_DEAL2.getTag(), FileTagEnum.CRITICAL_YING_DEAL2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.REPORT_WRITING.getTag(), FileTagEnum.REPORT_WRITING.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT.getTag(), FileTagEnum.WORK_REPORT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.GOVERMENT_REPORT.getTag(), FileTagEnum.GOVERMENT_REPORT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT1.getTag(), FileTagEnum.WORK_REPORT1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT2.getTag(), FileTagEnum.WORK_REPORT2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT3.getTag(), FileTagEnum.WORK_REPORT3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT4.getTag(), FileTagEnum.WORK_REPORT4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT5.getTag(), FileTagEnum.WORK_REPORT5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT6.getTag(), FileTagEnum.WORK_REPORT6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT7.getTag(), FileTagEnum.WORK_REPORT7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT8.getTag(), FileTagEnum.WORK_REPORT8.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT9.getTag(), FileTagEnum.WORK_REPORT9.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_REPORT10.getTag(), FileTagEnum.WORK_REPORT10.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.GOVERMENT_REPORT1.getTag(), FileTagEnum.GOVERMENT_REPORT1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.GOVERMENT_REPORT2.getTag(), FileTagEnum.GOVERMENT_REPORT2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.GOVERMENT_REPORT3.getTag(), FileTagEnum.GOVERMENT_REPORT3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.GOVERMENT_REPORT4.getTag(), FileTagEnum.GOVERMENT_REPORT4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.GOVERMENT_REPORT5.getTag(), FileTagEnum.GOVERMENT_REPORT5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.GOVERMENT_REPORT6.getTag(), FileTagEnum.GOVERMENT_REPORT6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.GOVERMENT_REPORT7.getTag(), FileTagEnum.GOVERMENT_REPORT7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.EVENT_RULE.getTag(), FileTagEnum.EVENT_RULE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT.getTag(), FileTagEnum.RECURSION_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FOOD_EVENT.getTag(), FileTagEnum.FOOD_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JOB_EVENT.getTag(), FileTagEnum.JOB_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.OTHER_EVENT.getTag(), FileTagEnum.OTHER_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.NATURE_EVENT.getTag(), FileTagEnum.NATURE_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.X_EVENT.getTag(), FileTagEnum.X_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LOSS_EVENT.getTag(), FileTagEnum.LOSS_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.BAD_EVENT.getTag(), FileTagEnum.BAD_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HOSPITAL_EVENT.getTag(), FileTagEnum.HOSPITAL_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.NO_REASON_EVENT.getTag(), FileTagEnum.NO_REASON_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.THINK_EVENT.getTag(), FileTagEnum.THINK_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT1.getTag(), FileTagEnum.RECURSION_EVENT1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT2.getTag(), FileTagEnum.RECURSION_EVENT2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT3.getTag(), FileTagEnum.RECURSION_EVENT3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT4.getTag(), FileTagEnum.RECURSION_EVENT4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT5.getTag(), FileTagEnum.RECURSION_EVENT5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT6.getTag(), FileTagEnum.RECURSION_EVENT6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT7.getTag(), FileTagEnum.RECURSION_EVENT7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT8.getTag(), FileTagEnum.RECURSION_EVENT8.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT9.getTag(), FileTagEnum.RECURSION_EVENT9.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT10.getTag(), FileTagEnum.RECURSION_EVENT10.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT11.getTag(), FileTagEnum.RECURSION_EVENT11.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT12.getTag(), FileTagEnum.RECURSION_EVENT12.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT13.getTag(), FileTagEnum.RECURSION_EVENT13.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT14.getTag(), FileTagEnum.RECURSION_EVENT14.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT15.getTag(), FileTagEnum.RECURSION_EVENT15.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT16.getTag(), FileTagEnum.RECURSION_EVENT16.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT17.getTag(), FileTagEnum.RECURSION_EVENT17.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT18.getTag(), FileTagEnum.RECURSION_EVENT18.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT19.getTag(), FileTagEnum.RECURSION_EVENT19.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT20.getTag(), FileTagEnum.RECURSION_EVENT20.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT21.getTag(), FileTagEnum.RECURSION_EVENT21.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT22.getTag(), FileTagEnum.RECURSION_EVENT22.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT23.getTag(), FileTagEnum.RECURSION_EVENT23.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT24.getTag(), FileTagEnum.RECURSION_EVENT24.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECURSION_EVENT25.getTag(), FileTagEnum.RECURSION_EVENT25.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STATE_TIME.getTag(), FileTagEnum.STATE_TIME.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CANCER_DISEASE.getTag(), FileTagEnum.CANCER_DISEASE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HEAD_DISEASE.getTag(), FileTagEnum.HEAD_DISEASE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.GREY_DISEASE.getTag(), FileTagEnum.GREY_DISEASE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DOG_DISEASE.getTag(), FileTagEnum.DOG_DISEASE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.POP_HEAD_DISEASE.getTag(), FileTagEnum.POP_HEAD_DISEASE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.MA_ZHEN.getTag(), FileTagEnum.MA_ZHEN.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SHUI_DOU.getTag(), FileTagEnum.SHUI_DOU.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SAI_XIAN.getTag(), FileTagEnum.SAI_XIAN.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DENG_GE_RE.getTag(), FileTagEnum.DENG_GE_RE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.ZENG_DUO_ZHENG.getTag(), FileTagEnum.ZENG_DUO_ZHENG.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.AIDS.getTag(), FileTagEnum.AIDS.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HUANG_RE_BING.getTag(), FileTagEnum.HUANG_RE_BING.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SHANG_HAN.getTag(), FileTagEnum.SHANG_HAN.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FU_SHANG.getTag(), FileTagEnum.FU_SHANG.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.NUE_JI.getTag(), FileTagEnum.NUE_JI.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HUO_LUAN.getTag(), FileTagEnum.HUO_LUAN.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.GAN_JUN.getTag(), FileTagEnum.GAN_JUN.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SHU_YI.getTag(), FileTagEnum.SHU_YI.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.TAN_JU.getTag(), FileTagEnum.TAN_JU.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.BAI_HOU.getTag(), FileTagEnum.BAI_HOU.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.BAI_RI_KE.getTag(), FileTagEnum.BAI_RI_KE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.XING_HONG_RE.getTag(), FileTagEnum.XING_HONG_RE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.NAO_JI_SUI.getTag(), FileTagEnum.NAO_JI_SUI.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LUO_XUAN_BING.getTag(), FileTagEnum.LUO_XUAN_BING.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HUI_GUI_RE.getTag(), FileTagEnum.HUI_GUI_RE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CANCER_DISEASE1.getTag(), FileTagEnum.CANCER_DISEASE1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CANCER_DISEASE2.getTag(), FileTagEnum.CANCER_DISEASE2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CANCER_DISEASE3.getTag(), FileTagEnum.CANCER_DISEASE3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CANCER_DISEASE4.getTag(), FileTagEnum.CANCER_DISEASE4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CANCER_DISEASE5.getTag(), FileTagEnum.CANCER_DISEASE5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FU_SHANG1.getTag(), FileTagEnum.FU_SHANG1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FU_SHANG2.getTag(), FileTagEnum.FU_SHANG2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SHU_YI1.getTag(), FileTagEnum.SHU_YI1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SHU_YI2.getTag(), FileTagEnum.SHU_YI2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE.getTag(), FileTagEnum.STUDY_DISEASE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE1.getTag(), FileTagEnum.STUDY_DISEASE1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE2.getTag(), FileTagEnum.STUDY_DISEASE2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE3.getTag(), FileTagEnum.STUDY_DISEASE3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE4.getTag(), FileTagEnum.STUDY_DISEASE4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE5.getTag(), FileTagEnum.STUDY_DISEASE5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE6.getTag(), FileTagEnum.STUDY_DISEASE6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE7.getTag(), FileTagEnum.STUDY_DISEASE7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE8.getTag(), FileTagEnum.STUDY_DISEASE8.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE9.getTag(), FileTagEnum.STUDY_DISEASE9.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE1_1.getTag(), FileTagEnum.STUDY_DISEASE1_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE1_2.getTag(), FileTagEnum.STUDY_DISEASE1_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE2_1.getTag(), FileTagEnum.STUDY_DISEASE2_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE2_2.getTag(), FileTagEnum.STUDY_DISEASE2_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE2_3.getTag(), FileTagEnum.STUDY_DISEASE2_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE3_1.getTag(), FileTagEnum.STUDY_DISEASE3_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE3_2.getTag(), FileTagEnum.STUDY_DISEASE3_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE3_3.getTag(), FileTagEnum.STUDY_DISEASE3_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE3_4.getTag(), FileTagEnum.STUDY_DISEASE3_4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE4_1.getTag(), FileTagEnum.STUDY_DISEASE4_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE4_2.getTag(), FileTagEnum.STUDY_DISEASE4_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE5_1.getTag(), FileTagEnum.STUDY_DISEASE5_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE5_2.getTag(), FileTagEnum.STUDY_DISEASE5_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE5_3.getTag(), FileTagEnum.STUDY_DISEASE5_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE5_4.getTag(), FileTagEnum.STUDY_DISEASE5_4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE6_1.getTag(), FileTagEnum.STUDY_DISEASE6_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE6_2.getTag(), FileTagEnum.STUDY_DISEASE6_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE7_1.getTag(), FileTagEnum.STUDY_DISEASE7_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE7_2.getTag(), FileTagEnum.STUDY_DISEASE7_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE7_3.getTag(), FileTagEnum.STUDY_DISEASE7_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE9_1.getTag(), FileTagEnum.STUDY_DISEASE9_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE9_2.getTag(), FileTagEnum.STUDY_DISEASE9_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE9_3.getTag(), FileTagEnum.STUDY_DISEASE9_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE9_4.getTag(), FileTagEnum.STUDY_DISEASE9_4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE9_5.getTag(), FileTagEnum.STUDY_DISEASE9_5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE9_6.getTag(), FileTagEnum.STUDY_DISEASE9_6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE9_7.getTag(), FileTagEnum.STUDY_DISEASE9_7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.STUDY_DISEASE9_8.getTag(), FileTagEnum.STUDY_DISEASE9_8.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CHECK_DRUGS.getTag(), FileTagEnum.CHECK_DRUGS.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG.getTag(), FileTagEnum.SMELL_WRONG.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DUO_HAN.getTag(), FileTagEnum.DUO_HAN.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SKIN_COLOR.getTag(), FileTagEnum.SKIN_COLOR.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG1.getTag(), FileTagEnum.SMELL_WRONG1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG2.getTag(), FileTagEnum.SMELL_WRONG2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG3.getTag(), FileTagEnum.SMELL_WRONG3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG4.getTag(), FileTagEnum.SMELL_WRONG4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG5.getTag(), FileTagEnum.SMELL_WRONG5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG6.getTag(), FileTagEnum.SMELL_WRONG6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG7.getTag(), FileTagEnum.SMELL_WRONG7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG8.getTag(), FileTagEnum.SMELL_WRONG8.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG9.getTag(), FileTagEnum.SMELL_WRONG9.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG10.getTag(), FileTagEnum.SMELL_WRONG10.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG11.getTag(), FileTagEnum.SMELL_WRONG11.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG12.getTag(), FileTagEnum.SMELL_WRONG12.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SMELL_WRONG13.getTag(), FileTagEnum.SMELL_WRONG13.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DUO_HAN1.getTag(), FileTagEnum.DUO_HAN1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DUO_HAN2.getTag(), FileTagEnum.DUO_HAN2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DUO_HAN3.getTag(), FileTagEnum.DUO_HAN3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DUO_HAN4.getTag(), FileTagEnum.DUO_HAN4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SKIN_COLOR1.getTag(), FileTagEnum.SKIN_COLOR1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SKIN_COLOR2.getTag(), FileTagEnum.SKIN_COLOR2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SKIN_COLOR3.getTag(), FileTagEnum.SKIN_COLOR3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SKIN_COLOR4.getTag(), FileTagEnum.SKIN_COLOR4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SKIN_COLOR5.getTag(), FileTagEnum.SKIN_COLOR5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SKIN_COLOR6.getTag(), FileTagEnum.SKIN_COLOR6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.COLLECT_TABLE.getTag(), FileTagEnum.COLLECT_TABLE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_COLLECT1.getTag(), FileTagEnum.DISEASE_COLLECT1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_COLLECT2.getTag(), FileTagEnum.DISEASE_COLLECT2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_COLLECT3.getTag(), FileTagEnum.DISEASE_COLLECT3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_COLLECT4.getTag(), FileTagEnum.DISEASE_COLLECT4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_COLLECT5.getTag(), FileTagEnum.DISEASE_COLLECT5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_COLLECT6.getTag(), FileTagEnum.DISEASE_COLLECT6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_COLLECT7.getTag(), FileTagEnum.DISEASE_COLLECT7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_COLLECT8.getTag(), FileTagEnum.DISEASE_COLLECT8.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DISEASE_COLLECT9.getTag(), FileTagEnum.DISEASE_COLLECT9.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FOOD_DRUGS_DEAL.getTag(), FileTagEnum.FOOD_DRUGS_DEAL.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FOOD_DRUGS_DEAL1.getTag(), FileTagEnum.FOOD_DRUGS_DEAL2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FOOD_DRUGS_DEAL2.getTag(), FileTagEnum.FOOD_DRUGS_DEAL2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FOOD_DRUGS_DEAL3.getTag(), FileTagEnum.FOOD_DRUGS_DEAL3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FOOD_DRUGS_DEAL4.getTag(), FileTagEnum.FOOD_DRUGS_DEAL4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FOOD_DRUGS_DEAL5.getTag(), FileTagEnum.FOOD_DRUGS_DEAL5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WATER_USE_FUNCTION.getTag(), FileTagEnum.WATER_USE_FUNCTION.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WATER_CHOOSE.getTag(), FileTagEnum.WATER_CHOOSE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_WATER.getTag(), FileTagEnum.KEEP_WATER.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DEAL_WATER.getTag(), FileTagEnum.DEAL_WATER.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CLEAR_WATER.getTag(), FileTagEnum.CLEAR_WATER.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.TRAN_WATER.getTag(), FileTagEnum.TRAN_WATER.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RECOVER_WATER.getTag(), FileTagEnum.RECOVER_WATER.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CHECK_WATER.getTag(), FileTagEnum.CHECK_WATER.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_WATER1.getTag(), FileTagEnum.KEEP_WATER1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_WATER2.getTag(), FileTagEnum.KEEP_WATER2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DEAL_WATER1.getTag(), FileTagEnum.DEAL_WATER1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DEAL_WATER2.getTag(), FileTagEnum.DEAL_WATER2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DEAL_WATER3.getTag(), FileTagEnum.DEAL_WATER3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DEAL_WATER4.getTag(), FileTagEnum.DEAL_WATER4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KILL_VIRUS.getTag(), FileTagEnum.KILL_VIRUS.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.DI_MIAN.getTag(), FileTagEnum.DI_MIAN.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.PAI_XIE.getTag(), FileTagEnum.PAI_XIE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.RONG_QI.getTag(), FileTagEnum.RONG_QI.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CE_SUO.getTag(), FileTagEnum.CE_SUO.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.ROOM_AIR.getTag(), FileTagEnum.ROOM_AIR.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WU_SHUI.getTag(), FileTagEnum.WU_SHUI.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LA_JI.getTag(), FileTagEnum.LA_JI.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CLOTH.getTag(), FileTagEnum.CLOTH.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CAN_JU.getTag(), FileTagEnum.CAN_JU.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FOOD.getTag(), FileTagEnum.FOOD.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.THING.getTag(), FileTagEnum.THING.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.BOOK.getTag(), FileTagEnum.BOOK.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.BING_REN.getTag(), FileTagEnum.BING_REN.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.ANIMAL_SHI_TI.getTag(), FileTagEnum.ANIMAL_SHI_TI.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.YUN_SHU_TOOL.getTag(), FileTagEnum.YUN_SHU_TOOL.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HAND_SKIN.getTag(), FileTagEnum.HAND_SKIN.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.NATURE_MONITOR.getTag(), FileTagEnum.NATURE_MONITOR.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.MIE_MONITOR.getTag(), FileTagEnum.MIE_MONITOR.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_USE.getTag(), FileTagEnum.WORK_USE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.MIE_MONITOR1.getTag(), FileTagEnum.MIE_MONITOR1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.MIE_MONITOR2.getTag(), FileTagEnum.MIE_MONITOR2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.MIE_MONITOR3.getTag(), FileTagEnum.MIE_MONITOR3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_USE1.getTag(), FileTagEnum.WORK_USE1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WORK_USE2.getTag(), FileTagEnum.WORK_USE2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.OPEN_VIRUS.getTag(), FileTagEnum.OPEN_VIRUS.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QING_VIRUS.getTag(), FileTagEnum.QING_VIRUS.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS.getTag(), FileTagEnum.JIN_SHU_VITUS.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LIN_VIRUS.getTag(), FileTagEnum.LIN_VIRUS.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.BEN_VIRUS.getTag(), FileTagEnum.BEN_VIRUS.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.MOUSE_VIRUS.getTag(), FileTagEnum.MOUSE_VIRUS.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QING_VIRUS1.getTag(), FileTagEnum.QING_VIRUS1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QING_VIRUS2.getTag(), FileTagEnum.QING_VIRUS2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QING_VIRUS3.getTag(), FileTagEnum.QING_VIRUS3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QING_VIRUS4.getTag(), FileTagEnum.QING_VIRUS4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QING_VIRUS5.getTag(), FileTagEnum.QING_VIRUS5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS1.getTag(), FileTagEnum.JIN_SHU_VITUS1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS2.getTag(), FileTagEnum.JIN_SHU_VITUS2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS3.getTag(), FileTagEnum.JIN_SHU_VITUS3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS4.getTag(), FileTagEnum.JIN_SHU_VITUS4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS5.getTag(), FileTagEnum.JIN_SHU_VITUS5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS6.getTag(), FileTagEnum.JIN_SHU_VITUS6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS7.getTag(), FileTagEnum.JIN_SHU_VITUS7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS8.getTag(), FileTagEnum.JIN_SHU_VITUS8.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS9.getTag(), FileTagEnum.JIN_SHU_VITUS9.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS10.getTag(), FileTagEnum.JIN_SHU_VITUS10.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.JIN_SHU_VITUS11.getTag(), FileTagEnum.JIN_SHU_VITUS11.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LIN_VIRUS1.getTag(), FileTagEnum.LIN_VIRUS1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LIN_VIRUS2.getTag(), FileTagEnum.LIN_VIRUS2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LIN_VIRUS3.getTag(), FileTagEnum.LIN_VIRUS3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.BEN_VIRUS1.getTag(), FileTagEnum.BEN_VIRUS1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.MOUSE_VIRUS1.getTag(), FileTagEnum.MOUSE_VIRUS1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.MOUSE_VIRUS2.getTag(), FileTagEnum.MOUSE_VIRUS2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.MOUSE_VIRUS3.getTag(), FileTagEnum.MOUSE_VIRUS3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION.getTag(), FileTagEnum.KEEP_FUNCTION.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION1.getTag(), FileTagEnum.KEEP_FUNCTION1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION2.getTag(), FileTagEnum.KEEP_FUNCTION2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION3.getTag(), FileTagEnum.KEEP_FUNCTION3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION4.getTag(), FileTagEnum.KEEP_FUNCTION4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION5.getTag(), FileTagEnum.KEEP_FUNCTION5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION6.getTag(), FileTagEnum.KEEP_FUNCTION6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION7.getTag(), FileTagEnum.KEEP_FUNCTION7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION8.getTag(), FileTagEnum.KEEP_FUNCTION8.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION9.getTag(), FileTagEnum.KEEP_FUNCTION9.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION10.getTag(), FileTagEnum.KEEP_FUNCTION10.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION11.getTag(), FileTagEnum.KEEP_FUNCTION11.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION12.getTag(), FileTagEnum.KEEP_FUNCTION12.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION13.getTag(), FileTagEnum.KEEP_FUNCTION13.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION14.getTag(), FileTagEnum.KEEP_FUNCTION14.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION15.getTag(), FileTagEnum.KEEP_FUNCTION15.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.KEEP_FUNCTION16.getTag(), FileTagEnum.KEEP_FUNCTION16.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HIDDEN_EVENT.getTag(), FileTagEnum.HIDDEN_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.MEI_QI_EVENT.getTag(), FileTagEnum.MEI_QI_EVENT.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HU_XI.getTag(), FileTagEnum.HU_XI.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CANG_DAO.getTag(), FileTagEnum.CANG_DAO.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.XIAN_CHANG.getTag(), FileTagEnum.XIAN_CHANG.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HU_XI1.getTag(), FileTagEnum.HU_XI1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HU_XI2.getTag(), FileTagEnum.HU_XI2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.HU_XI3.getTag(), FileTagEnum.HU_XI3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CANG_DAO1.getTag(), FileTagEnum.CANG_DAO1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CANG_DAO2.getTag(), FileTagEnum.CANG_DAO2.getTitleMessage());
        mList.add(queryBean);


        // ==================
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL.getTag(), FileTagEnum.WEN_CONTROL.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1.getTag(), FileTagEnum.WEN_CONTROL1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2.getTag(), FileTagEnum.WEN_CONTROL2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_1.getTag(), FileTagEnum.WEN_CONTROL1_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2.getTag(), FileTagEnum.WEN_CONTROL1_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_1.getTag(), FileTagEnum.WEN_CONTROL2_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_2.getTag(), FileTagEnum.WEN_CONTROL2_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_3.getTag(), FileTagEnum.WEN_CONTROL2_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_4.getTag(), FileTagEnum.WEN_CONTROL2_4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5.getTag(), FileTagEnum.WEN_CONTROL2_5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_6.getTag(), FileTagEnum.WEN_CONTROL2_6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_7.getTag(), FileTagEnum.WEN_CONTROL2_7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_1.getTag(), FileTagEnum.WEN_CONTROL1_2_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_2.getTag(), FileTagEnum.WEN_CONTROL1_2_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_3.getTag(), FileTagEnum.WEN_CONTROL1_2_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_4.getTag(), FileTagEnum.WEN_CONTROL1_2_4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_5.getTag(), FileTagEnum.WEN_CONTROL1_2_5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_6.getTag(), FileTagEnum.WEN_CONTROL1_2_6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_5_1.getTag(), FileTagEnum.WEN_CONTROL1_2_5_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_5_2.getTag(), FileTagEnum.WEN_CONTROL1_2_5_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_5_3.getTag(), FileTagEnum.WEN_CONTROL1_2_5_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_5_4.getTag(), FileTagEnum.WEN_CONTROL1_2_5_4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_5_5.getTag(), FileTagEnum.WEN_CONTROL1_2_5_5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_5_6.getTag(), FileTagEnum.WEN_CONTROL1_2_5_6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_5_7.getTag(), FileTagEnum.WEN_CONTROL1_2_5_7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_6_1.getTag(), FileTagEnum.WEN_CONTROL1_2_6_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_6_2.getTag(), FileTagEnum.WEN_CONTROL1_2_6_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL1_2_6_3.getTag(), FileTagEnum.WEN_CONTROL1_2_6_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_1.getTag(), FileTagEnum.WEN_CONTROL2_5_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_2.getTag(), FileTagEnum.WEN_CONTROL2_5_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_3.getTag(), FileTagEnum.WEN_CONTROL2_5_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_1_1.getTag(), FileTagEnum.WEN_CONTROL2_5_1_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_1_2.getTag(), FileTagEnum.WEN_CONTROL2_5_1_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_1_3.getTag(), FileTagEnum.WEN_CONTROL2_5_1_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_2_1.getTag(), FileTagEnum.WEN_CONTROL2_5_2_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_2_2.getTag(), FileTagEnum.WEN_CONTROL2_5_2_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_3_1.getTag(), FileTagEnum.WEN_CONTROL2_5_3_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_3_2.getTag(), FileTagEnum.WEN_CONTROL2_5_3_2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_3_3.getTag(), FileTagEnum.WEN_CONTROL2_5_3_3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_3_4.getTag(), FileTagEnum.WEN_CONTROL2_5_3_4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_3_5.getTag(), FileTagEnum.WEN_CONTROL2_5_3_5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_5_3_6.getTag(), FileTagEnum.WEN_CONTROL2_5_3_6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_7_1.getTag(), FileTagEnum.WEN_CONTROL2_7_1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.WEN_CONTROL2_7_2.getTag(), FileTagEnum.WEN_CONTROL2_7_2.getTitleMessage());
        mList.add(queryBean);

        // new add
        queryBean = new QueryBean(FileTagEnum.SHA_CHILD_CONG.getTag(), FileTagEnum.SHA_CHILD_CONG.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CHENG_YING_KONG_ZHI.getTag(), FileTagEnum.CHENG_YING_KONG_ZHI.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.SHA_CHILD_CONG1.getTag(), FileTagEnum.SHA_CHILD_CONG1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CHENG_YING_KONG_ZHI1.getTag(), FileTagEnum.CHENG_YING_KONG_ZHI1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CHENG_YING_KONG_ZHI2.getTag(), FileTagEnum.CHENG_YING_KONG_ZHI2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.CHENG_YING_KONG_ZHI3.getTag(), FileTagEnum.CHENG_YING_KONG_ZHI3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG1.getTag(), FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG2.getTag(), FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG3.getTag(), FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG4.getTag(), FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG5.getTag(), FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG6.getTag(), FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG7.getTag(), FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG8.getTag(), FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG8.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG9.getTag(), FileTagEnum.LINC_CHUANG_ZHENG_ZHUANG9.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FUNCTION1.getTag(), FileTagEnum.FUNCTION1.getTitleMessage());
        mList.add(queryBean);


        queryBean = new QueryBean(FileTagEnum.FUNCTION2.getTag(), FileTagEnum.FUNCTION2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FUNCTION3.getTag(), FileTagEnum.FUNCTION3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FUNCTION4.getTag(), FileTagEnum.FUNCTION4.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FUNCTION5.getTag(), FileTagEnum.FUNCTION5.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FUNCTION6.getTag(), FileTagEnum.FUNCTION6.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.FUNCTION7.getTag(), FileTagEnum.FUNCTION7.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.REASON_STEP.getTag(), FileTagEnum.REASON_STEP.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_DISEASE.getTag(), FileTagEnum.QUICK_DISEASE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_NO_DISEASE.getTag(), FileTagEnum.QUICK_NO_DISEASE.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.LIN_CHUANG_TE_ZHENG.getTag(), FileTagEnum.LIN_CHUANG_TE_ZHENG.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_NO_DISEASE1.getTag(), FileTagEnum.QUICK_NO_DISEASE1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_NO_DISEASE2.getTag(), FileTagEnum.QUICK_NO_DISEASE2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_NO_DISEASE3.getTag(), FileTagEnum.QUICK_NO_DISEASE3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_DISEASE1.getTag(), FileTagEnum.QUICK_DISEASE1.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_DISEASE2.getTag(), FileTagEnum.QUICK_DISEASE2.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_DISEASE3.getTag(), FileTagEnum.QUICK_DISEASE3.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_NO_DISEASE21.getTag(), FileTagEnum.QUICK_NO_DISEASE21.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_NO_DISEASE22.getTag(), FileTagEnum.QUICK_NO_DISEASE22.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_NO_DISEASE31.getTag(), FileTagEnum.QUICK_NO_DISEASE31.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.QUICK_NO_DISEASE32.getTag(), FileTagEnum.QUICK_NO_DISEASE32.getTitleMessage());
        mList.add(queryBean);

        queryBean = new QueryBean(FileTagEnum.THINGS_PREPARE_FLAG31.getTag(), FileTagEnum.THINGS_PREPARE_FLAG31.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.THINGS_PREPARE_FLAG32.getTag(), FileTagEnum.THINGS_PREPARE_FLAG32.getTitleMessage());
        mList.add(queryBean);
        queryBean = new QueryBean(FileTagEnum.THINGS_PREPARE_FLAG33.getTag(), FileTagEnum.THINGS_PREPARE_FLAG33.getTitleMessage());
        mList.add(queryBean);

        queryBean = new QueryBean(FileTagEnum.PEOPLE_DUTY.getTag(), FileTagEnum.PEOPLE_DUTY.getTitleMessage());
        mList.add(queryBean);
        return mList;
    }

    public List<QueryBean> getResultData(String query) {
        List<QueryBean> queryBeans = QueryFactory.getInstance().getRepository();
        List<QueryBean> list = new ArrayList<>();
        for (QueryBean queryBean : queryBeans) {
            String title = queryBean.getTitle();
            if (title.contains(query)) {
                list.add(queryBean);
            }
        }
        return list;
    }

}
